login:
    path: /
    controller: App\Controller\ConnexionController::renderingConnexionPage

dashboard:
    path: /dashboard
    controller: App\Controller\DashBoardController::renderingDashboard

usersList:
    path: /users/list
    controller: App\Controller\UsersListController::usersListRender

devicesList:
    path: /devices/list
    controller: App\Controller\DevicesListController::devicesListRender

userPage:
    path: /user/{id}
    controller: App\Controller\UserController::userRender

devicePage:
    path: /device/{id}
    controller: App\Controller\DeviceController::deviceRender

addDevice:
    path: /user/{userId}/device/{deviceId}/add
    controller: App\Controller\UserController::AddDevice

addUser:
    path: /device/{deviceId}/user/{userId}/add
    controller: App\Controller\DeviceController::AddUser

unsubDevice:
    path: /user/{userId}/device/{deviceId}/unsub
    controller: App\Controller\UserController::UnsubDevice

unsubUser:
    path: /device/{deviceId}/user/{userId}/unsub
    controller: App\Controller\DeviceController::UnsubUser