login:
    path: /
    controller: App\Controller\ConnexionController::renderingConnexionPage

dashboard:
    path: /dashboard
    controller: App\Controller\DashBoardController::renderingDashboard

usersList:
    path: /users/list
    controller: App\Controller\UsersListController::usersListRender

devicesList:
    path: /devices/list
    controller: App\Controller\DevicesListController::devicesListRender